### ISSUE TITLE
completion_suppress_append it doesn't seem to work

### ISSUE THREAD

**Issue by vbextreme** [hirooih/perl-trg#22]
**Describe the bug**
I wanted to eliminate the space added after pressing the tab key, I set completion_suppress_append to 1 but it doesn't seem to work.

**To Reproduce**
```
use strict;
use warnings;
require Term::ReadLine;

my $term = Term::ReadLine->new("");
$term->ornaments(0);

sub pizza_completion{
	my ($text, $line, $start, $end) = @_;
	return "pizza" if "pizza" =~ /^$text/;
}

$term->Attribs->{completion_suppress_append} = 1;
#$term->Attribs->{attempted_completion_function} = \&pizza_completion;
$term->Attribs->{completion_function} = \&pizza_completion;

print "read: '" . $term->readline("> ") . "'\n";
```
output:
```
read: 'pizza '
```

**Expected behavior**
output without space:
```
read: 'pizza'
```

**Please complete the following information:**
   - perl v5.38
   - rxvt-unicode-256color

**Additional context**
I used prebuild version on arch linux called perl-term-readline-gnu v1.46

**Comment by hirooih** [comment]
From [the GNU Readline Library Manual](https://tiswww.case.edu/php/chet/readline/readline.html):

> Variable: int rl_completion_suppress_append
>
> If non-zero, rl_completion_append_character is not appended to matches at the end of the command line, as described above. It is set to 0 before any application-specific completion function is called, and **may only be changed within such a function**.

The following is what you want.

```perl
#!/usr/bin/perl
use strict;
use warnings;
use Term::ReadLine;

my $term = Term::ReadLine->new("");
$term->ornaments(0);

sub pizza_completion{
    my ($text, $line, $start) = @_;
    $term->Attribs->{completion_suppress_append} = 1;
    return ('pizza', 'pasta', 'beer');
}

$term->Attribs->{completion_function} = \&pizza_completion;

print "read: '" . $term->readline("> ") . "'\n";
```

I hope this helps.

**Comment by vbextreme** [comment]
I misread the documentation, thank you very much it works perfectly.

**Comment by hirooih** [comment]
> I misread the documentation, thank you very much it works perfectly.

I'm glad hear that!
Enjoy programming!
